STOP_INPUT = "stop"

MAZE = "1"
GAMES = [MAZE]

WINDOW_WIDTH, WINDOW_HEIGHT = 1500, 1500
# Grid size for maze:
GRID_HEIGHT = 15
GRID_WIDTH = 15
# Frame size for maze:
FRAME_HEIGHT = int(WINDOW_HEIGHT / GRID_HEIGHT)
FRAME_WIDTH = int(WINDOW_WIDTH / GRID_WIDTH)
MAZE_QUESTION_MAX_AMOUNT = 5
